In [1]:
#load the iris dataset
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
#The feature matrix for the Iris data is X

X = iris.data

#and the response data is Y 

Y = iris.target

In [3]:
print('X_dimensionality', X.shape)
print('Y_dimensionality', Y.shape)

X_dimensionality (150, 4)
Y_dimensionality (150,)


In [4]:
import pandas as pd
data = pd.DataFrame(X, columns = iris.feature_names)

In [5]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X=X,y=Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [8]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
simple_train = ['call you tonight', 'Call me a cab', 'please call me.. please']

We will use CountVectoriser from SKlearn. 

In order to do so, we have to go through 4 steps:
1. Import
2. Instantiate
3. Fit
4. Transform

In [10]:
#Next, I will import and instantiate CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import TreebankWordTokenizer
from nltk.tokenize import RegexpTokenizer

#instantiate CountVectorizer
vect = CountVectorizer(ngram_range=(1,3), stop_words='english', tokenizer=RegexpTokenizer(r'\w+').tokenize)

In [11]:
#Fit
#learn the vocabulary of the training data
vect.fit(simple_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 3), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method RegexpTokenizer.tokenize of RegexpTokenizer(pattern='\\w+', gaps=False, discard_empty=True, flags=<RegexFlag.UNICODE|DOTALL|MULTILINE: 56>)>,
        vocabulary=None)

In [12]:
vect.get_feature_names()

['cab', 'tonight']

In [13]:
#tranform training data into a 'document-term matix'
simple_train_dtm = vect.transform(simple_train)

In [14]:
simple_train_dtm

<3x2 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [15]:
#convert sparse matrix into a dense matrix
simple_train_dtm.toarray()

array([[0, 1],
       [1, 0],
       [0, 0]])

In [16]:
#examine the vocabulary and document-term matrix together
pd.DataFrame(simple_train_dtm.toarray(),columns=vect.get_feature_names())

cab  tonight
0    0        1
1    1        0
2    0        0

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import TreebankWordTokenizer

#instantiate CountVectorizer
vect = CountVectorizer(ngram_range=(1,3), stop_words='english', tokenizer=TreebankWordTokenizer().tokenize)

In [18]:
print('sparse matrix')
print(simple_train_dtm)

sparse matrix
  (0, 1)	1
  (1, 0)	1


In [19]:
print('dense matrix')
print(simple_train_dtm.toarray())

dense matrix
[[0 1]
 [1 0]
 [0 0]]


Another project

In [20]:
path = '/Users/tawfiq/Downloads/sms.tsv'
Features = ['label','message']
sms = pd.read_table(path, header=None, names=Features)

In [21]:
sms.shape

(5572, 2)

In [22]:
#The dataframe contains a label for determining whether the sms is ham or spam message
sms.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [23]:
X = sms.message
Y = sms.label
print('The shape of the message data')
print(X.shape)
print('The shape of the labels')
print(Y.shape)

The shape of the message data
(5572,)
The shape of the labels
(5572,)


X is a one-dimensional matrix because it will be passed to a Vecotrizer to become a 2D matrix
You must always start with a 1D matrix as input to the vectorizer in oder to get a 2D matrix as transformed output

In [24]:
#Split X and Y into training and test datasets
#randomstate = 1 for reproduceability 
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4179,)
(1393,)
(4179,)
(1393,)


/Users/tawfiq/Desktop/ThrowawayAccountRandomForest/env/lib/python3.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Since we want to model the real problem, we will vectorize only after splitting train, test datasets

In [25]:
vect = CountVectorizer()

In [26]:
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

In [27]:
X_train_dtm

<4179x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [28]:
X_test_dtm = vect.transform(X_test)

In [29]:
X_test_dtm

<1393x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

The multinomial Naive Bayes classifier is suitable for classification with discrete features (e.g., word counts for text classification). The multinomial distribution normally requires integer feature counts. However, in practice, fractional counts such as tf-idf may also work.

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
nb = MultinomialNB()

In [32]:
%time nb.fit(X_train_dtm, y_train)

CPU times: user 16.6 ms, sys: 2.19 ms, total: 18.8 ms
Wall time: 27 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
print(y_test.value_counts())
# there is a majority class of 0 here, hence the classes are skewed

ham     1208
spam     185
Name: label, dtype: int64


In [36]:
#print the confusion matrix
from sklearn import metrics 

y_pred_class = nb.predict(X_test_dtm)
print(metrics.accuracy_score(y_test, y_pred_class))
metrics.confusion_matrix(y_test, y_pred_class )

0.9885139985642498


array([[1203,    5],
       [  11,  174]])

confusion matrix:
[TN FP
 FN TP]

In [37]:
# print message text for the false positives (ham incorrectly classified as spam)

X_test[y_pred_class > y_test]

# alternative less elegant but easier to understand
# X_test[(y_pred_class==1) & (y_test==0)]

574               Waiting for your call.
3375             Also andros ice etc etc
45      No calls..messages..missed calls
3415             No pic. Please re-send.
1988    No calls..messages..missed calls
Name: message, dtype: object

In [38]:
#print message text for false negatives 

X_test[y_pred_class< y_test]

3132    LookAtMe!: Thanks for your purchase of a video...
5       FreeMsg Hey there darling it's been 3 week's n...
3530    Xmas & New Years Eve tickets are now on sale f...
684     Hi I'm sue. I am 20 years old and work as a la...
1875    Would you like to see my XXX pics they are so ...
1893    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
4298    thesmszone.com lets you send free anonymous an...
4949    Hi this is Amy, we will be sending you a free ...
2821    INTERFLORA - “It's not too late to order Inter...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
4514    Money i have won wining number 946 wot do i do...
Name: message, dtype: object

In [39]:
X_test[y_pred_class == y_test]

1078                         Yep, by the pretty sculpture
4028        Yes, princess. Are you going to make me moan?
958                            Welp apparently he retired
4642                                              Havent.
4674    I forgot 2 ask ü all smth.. There's a card on ...
5461    Ok i thk i got it. Then u wan me 2 come now or...
4210    I want kfc its Tuesday. Only buy 2 meals ONLY ...
4216                           No dear i was sleeping :-P
1603                            Ok pa. Nothing problem:-)
1504                      Ill be there on  &lt;#&gt;  ok.
1783    My uncles in Atlanta. Wish you guys a great se...
3465                                             My phone
5534                         Ok which your another number
4267    The greatest test of courage on earth is to be...
2498    Dai what this da.. Can i send my resume to thi...
4259                        I am late. I will be there at
147     FreeMsg Why haven't you replied to my text? I'...
141           

In [41]:
#print the predicted probabilities for X_test_dtm (poorly calibrated)
#left column, probability class 0
#right column, probability class 1
#we only need the right column
y_pred_prob = nb.predict_proba(X_test_dtm)[:,1]
y_pred_prob

array([2.87744864e-03, 1.83488846e-05, 2.07301295e-03, ...,
       1.09026171e-06, 1.00000000e+00, 3.98279868e-09])